---

- hosts: localhost
  connection: local
  # gather_facts: no
  become: false
  vars_files:
    - default_vars.yml

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      # when: ansible_machine == "x86_64"
    
    - name: Installing Homebrew Cask Packages
      community.general.homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
        accept_external_apps: True
      # when: ansible_machine == "x86_64"
      # register: result
      # until: result is successful

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      # when: ansible_machine == "x86_64"
      # register: result
      # until: result is successful

    # - name: Updating Homebrew M1 Pro
    #   homebrew:
    #     update_homebrew: yes
    #     upgrade_all: yes
    #   environment:
    #     PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
    #   when: ansible_machine == "arm64"
    
    # - name: Installing Homebrew Cask Packages M1 Pro
    #   community.general.homebrew_cask:
    #     name: "{{ brew_cask_packages }}"
    #     state: present
    #     accept_external_apps: True
    #   environment:
    #     PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
    #   when: ansible_machine == "arm64"
    #     # register: result
    #   # until: result is successful

    # - name: Installing Homebrew Packages M1 Pro
    #   homebrew:
    #     name: "{{ brew_packages }}"
    #     state: present
    #   environment:
    #     PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
    #   when: ansible_machine == "arm64"
    #     # register: result
    #   # until: result is successful

    - name: zshrc
      copy:
        src: files/zshrc
        dest: /Users/nick/.zshrc
        owner: nick
        group: nick
        mode: "0775"
  
    - name: vimrc  
      copy:
        src: files/vimrc
        dest: /Users/nick/.vimrc
        owner: nick
        group: nick
        mode: "0775"

    - name: Clone ohmyzsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /Users/nick/.oh-my-zsh
        single_branch: yes
        version: main

    - name: clone zsh-autosuggestions  
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /Users/nick/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        single_branch: yes
        version: main
    
    - name: clone zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /Users/nick/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        single_branch: yes
        version: main
