---

- hosts: all
  gather_facts: no
  # become: false
  vars_files:
    - default_vars.yml

  pre_tasks:
    - name: Send a magic Wake-on-LAN packet to HackPro
      wakeonlan:
        mac: 'b4:2e:99:fc:96:2e'
        broadcast: 192.168.11.255
      delegate_to: localhost

    - name: Send a magic Wake-on-LAN packet to RackPro
      wakeonlan:
        mac: '10:c3:7b:4f:74:a6'
        broadcast: 192.168.11.255
      delegate_to: localhost   

    - name: Send a magic Wake-on-LAN packet to MBP14
      wakeonlan:
        mac: 'f0:2f:4b:0b:66:ef'
        broadcast: 192.168.11.255
      delegate_to: localhost

    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 10
        timeout: 30

    - name: Gather facts for first time
      setup:

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes    
    
    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
        accept_external_apps: True
      register: result
      until: result is successful

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
