---

- hosts: all
  gather_facts: no
  vars_files:
    - default_vars.yml

  pre_tasks:
    - name: Send a magic Wake-on-LAN packet to HackPro
      wakeonlan:
        mac: 'b4:2e:99:fc:96:30'
        broadcast: 192.168.11.255
      delegate_to: localhost

    - name: Send a magic Wake-on-LAN packet to RackPro
      wakeonlan:
        mac: '10:c3:7b:4f:74:a6'
        broadcast: 192.168.11.255
      delegate_to: localhost

    - name: Send a magic Wake-on-LAN packet to MBP14
      wakeonlan:
        mac: 'f0:2f:4b:0b:66:ef'
        broadcast: 192.168.11.255
      delegate_to: localhost

    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 5
        timeout: 15

    - name: Keep Awake
      command: caffeinate -u -t 1
      # Turns on Displays to keep computers awake

    - name: Gather facts for first time
      setup:
        
    # - name: Check if Homebrew is already installed
    #   stat:
    #     path: /usr/local/bin/brew
    #   register: b
    #   when: ansible_machine == "x86_64"
 
    # - name: Install Homebrew
    #   script: install-homebrew.sh
    #   when: b.stat.exists == False and ansible_machine == "x86_64"

    - name: Copy and Execute the script 
      script: ~/git/dotfiles/install-dotfiles/macos-zsh.sh
  
  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      when: ansible_machine == "x86_64"
    
    - name: Installing Homebrew Cask Packages
      community.general.homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
        accept_external_apps: True
      when: ansible_machine == "x86_64"

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      when: ansible_machine == "x86_64"

    - name: Updating Homebrew M1 Pro
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      environment:
        PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
      when: ansible_machine == "arm64"
    
    - name: Installing Homebrew Cask Packages M1 Pro
      community.general.homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
        accept_external_apps: True
      environment:
        PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
      when: ansible_machine == "arm64"

    - name: Installing Homebrew Packages M1 Pro
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      environment:
        PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}
      when: ansible_machine == "arm64"