---

- hosts: all
  gather_facts: no
  vars_files:
    - default_vars.yml

  pre_tasks:
    - name: Send a magic Wake-on-LAN packet to HackPro
      wakeonlan:
        mac: 'b4:2e:99:fc:96:30'
        broadcast: 192.168.11.255
      delegate_to: localhost
      when: inventory_hostname == "hackpro"

    - name: Send a magic Wake-on-LAN packet to RackPro
      wakeonlan:
        mac: '10:c3:7b:4f:74:a6'
        broadcast: 192.168.11.255
      delegate_to: localhost
      when: inventory_hostname == "rackpro"

    - name: Send a magic Wake-on-LAN packet to MBP14
      wakeonlan:
        mac: 'f0:2f:4b:0b:66:ef'
        broadcast: 192.168.11.255
      delegate_to: localhost
      when: inventory_hostname == "mbp14"

    - name: Send a magic Wake-on-LAN packet to MBP13
      wakeonlan:
        mac: '98:01:a7:a6:96:75'
        broadcast: 192.168.11.255
      delegate_to: localhost
      when: inventory_hostname == "macos-mbp13"

    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 5
        timeout: 15

    - name: Keep Awake
      command: caffeinate -u -t 1
      # Turns on Displays to keep computers awake

    - name: Gather facts for first time
      setup:

- hosts: all
  roles:
    - base